import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  universalAppSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
      collapsible: true,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Architecture',
      link: { type: 'doc', id: 'architecture' },
      items: ['architecture'],
      collapsible: true,
      collapsed: true,
    },
    {
      type: 'category',
      label: 'ADRs',
      link: { type: 'doc', id: 'architectural-decision-records' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'architectural-decision-records',
        },
      ],
      collapsible: true,
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      link: { type: 'doc', id: 'troubleshooting' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'troubleshooting',
        },
      ],
      collapsible: true,
      collapsed: true,
    },
  ],
};

export default sidebars;
