jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Other steps...
      - run: pnpm install --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint test build
